[Bootloader]
type = SDBOOT
efi_dir = systemd
menu_auto_hide = False

[Storage]
default_scheme = BTRFS
btrfs_compression = zstd:1
luks_version = luks2
default_partitioning =
    / (min 8 GiB)
    /home (min 1 GiB, free 50 GiB)

[Storage Constraints]
req_partition_sizes =
    / 8 GiB
    /boot/efi 256 MiB

[User Interface]
webui_web_engine = /usr/local/libexec/gaokun-install-browser
# The launcher explicitly selects the fedora-workstation profile.

[Target]
system_root = /mnt/sysroot
