Syntax 4

SectionUseCase."HiFi" {
	File "/Qualcomm/gaokun-dp-audio/HiFi.conf"
	Comment "HiFi quality Music."
}

SectionUseCase."HiFiDP0" {
	File "/Qualcomm/gaokun-dp-audio/HiFi-DP0.conf"
	Comment "Internal audio and USB-C DisplayPort 0"
}

SectionUseCase."HiFiDP1" {
	File "/Qualcomm/gaokun-dp-audio/HiFi-DP1.conf"
	Comment "Internal audio and USB-C DisplayPort 1"
}

BootSequence [
	cset "name='SpkrLeft PA Volume' 12"
	cset "name='SpkrRight PA Volume' 12"
	cset "name='HPHL Volume' 2"
	cset "name='HPHR Volume' 2"
	cset "name='ADC2 Volume' 10"
]

Include.card-init.File "/lib/card-init.conf"
Include.ctl-remap.File "/lib/ctl-remap.conf"
Include.wcd-init.File "/codecs/wcd938x/init.conf"
Include.wsa-init.File "/codecs/wsa883x/init.conf"
Include.wsam-init.File "/codecs/qcom-lpass/wsa-macro/init.conf"
Include.rxm-init.File "/codecs/qcom-lpass/rx-macro/init.conf"
