# Shared by fresh installs, image builds and kernel RPM upgrades.
hostonly="no"
hostonly_cmdline="no"
add_dracutmodules+=" crypt "
add_drivers+=" dm_crypt btrfs nvme usbhid i2c-hid-of hid-multitouch msm panel-himax-hx83121a himax_hx83121a_spi "
